# Welcome to Jekyll!
#

# Site settings
title: Pioneer Robotics
description: |
  Our mission is to inspire young people at Pioneer Middle School 
  to be science and technology leaders by engaging them in hands-on 
  programs that build science, engineering and technology skills and 
  inspire innovation.
owner: Patrick Hurley
first_published: 2016 
email: pioneer.ftc.robotics@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://plymouth-canton-ftc.org/pioneer" # the base hostname & protocol for your site
social:
  email: mailto:pioneer.ftc.robotics@gmail.com
  github: https://github.com/orgs/FTC10262/dashboard
  twitter: https://twitter.com/PioneerFTC
  facebook-official: https://www.facebook.com/pioneer.ftc.robotics/
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
